name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 5.0.0
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.5
  get_thumbnail_video: ^0.7.3
  flutter_native_video_trimmer:
    git:
      url: https://github.com/sugith-pi/flutter_native_video_trimmer
      ref: e2b8d022644a196e545f51a80079cacef4ac05db
  path_provider: ^2.1.5
  intl: ^0.20.2
  path: ^1.9.1
  transparent_image: ^2.0.1
  image: ^4.5.4

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
